services:
  - type: web
    name: simulateur-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    repo: https://github.com/Aksl-Ushindi/simutest-frontend
    branch: main
    autoDeploy: true
